name: ROS Noetic Build and Launch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_DISTRO: noetic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS Noetic
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-noetic.list'
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install -y ros-noetic-desktop

          echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
          source ~/.bashrc

          sudo apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

          sudo rosdep init
          rosdep update

      - name: Install ROS packages with rosdep
        run: |
          source /opt/ros/noetic/setup.bash
          sudo rosdep init
          rosdep update
          ln -s $GITHUB_WORKSPACE ~/test_ws/src
          cd ~/test_ws
          rosdep install --from-paths src --ignore-src -r -s
          rosdep install --from-paths src --ignore-src -ry

      - name: Build workspace with colcon
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ~/test_ws
          colcon build
          source install/setup.bash

      - name: Launch rrbot_world
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ~/test_ws
          source install/setup.bash
          roslaunch rrbot_gazebo rrbot_world.launch
