name: ROS Noetic Build and Launch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_DISTRO: noetic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS Noetic
        id: setup_ros
        uses: cachix/install-nix-action@v14

      - name: Restore ROS setup cache
        uses: actions/cache@v2
        with:
          path: /opt/ros
          key: ${{ runner.os }}-ros-${{ hashFiles('**/ros-install.sh') }}

      - name: Build workspace with colcon
        run: |
          cd ~/test_ws
          colcon build
          source install/setup.bash

      - name: Save ROS setup cache
        uses: actions/cache@v2
        with:
          path: /opt/ros
          key: ${{ runner.os }}-ros-${{ hashFiles('**/ros-install.sh') }}

      - name: Launch rrbot_world
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ~/test_ws
          source install/setup.bash
          roslaunch rrbot_gazebo rrbot_world.launch
