name: ROS Noetic Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS Noetic
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-noetic.list'
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install -y ros-noetic-desktop

          echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
          source ~/.bashrc

          sudo apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

          sudo rosdep init
          rosdep update

      - name: Build workspace with colcon
        run: |
          cd ~/test_ws
          colcon build
